# Generated by Django 2.1.5 on 2019-03-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='guardian',
            name='profession',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
